### ISSUE TITLE
eclipse plugin error when TFS team favorit build is set

### ISSUE THREAD

**Issue by PeterJakubik** [Microsoft/team-explorer-everywhere#175]
Hi 
There is a bad cast in TeamExplorerBuildsFavoritesSection.java on line 264. In Eclipse TFS plugin it causes an error if TFS Team Favorits build is set.

https://github.com/Microsoft/team-explorer-everywhere/tree/master/source/com.microsoft.tfs.client.common.ui.teambuild/src/com/microsoft/tfs/client/common/ui/teambuild/teamexplorer/sections/TeamExplorerBuildsFavoritesSection.java#L264

Issue already here [https://developercommunity.visualstudio.com/content/problem/22021/tee-141111-move-build-definition-to-team-favorites.html](url)

Here is the eclipse stack trace

!ENTRY org.eclipse.jface 4 2 2017-03-02 10:26:33.542
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.ClassCastException: com.microsoft.alm.teamfoundation.build.webapi.BuildDefinitionReference cannot be cast to com.microsoft.alm.teamfoundation.build.webapi.BuildDefinition
	at com.microsoft.tfs.client.common.ui.teambuild.teamexplorer.sections.TeamExplorerBuildsFavoritesSection$MyLabelProvider.getColumnImage(TeamExplorerBuildsFavoritesSection.java:264)
	at org.eclipse.jface.viewers.TableColumnViewerLabelProvider.update(TableColumnViewerLabelProvider.java:67)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:141)
	at org.eclipse.jface.viewers.AbstractTableViewer.doUpdateItem(AbstractTableViewer.java:382)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:474)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2170)
	at org.eclipse.jface.viewers.AbstractTableViewer.createItem(AbstractTableViewer.java:273)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefreshAll(AbstractTableViewer.java:715)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefresh(AbstractTableViewer.java:607)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefresh(AbstractTableViewer.java:599)
	at org.eclipse.jface.viewers.AbstractTableViewer.lambda$0(AbstractTableViewer.java:561)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1458)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1419)
	at org.eclipse.jface.viewers.AbstractTableViewer.inputChanged(AbstractTableViewer.java:561)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:286)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1696)
	at com.microsoft.tfs.client.common.ui.teambuild.teamexplorer.sections.TeamExplorerBuildsFavoritesSection.getSectionContent(TeamExplorerBuildsFavoritesSection.java:137)
	at com.microsoft.tfs.client.common.ui.controls.teamexplorer.TeamExplorerBaseControl$SectionLoadJobChangeListener$1.run(TeamExplorerBaseControl.java:530)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

Peter

**Comment by jeffyoung** [comment]
Thanks for reporting Peter.  (We've filed a bug based on the information left on the VS Developer Community site.)  In the meantime, is the workaround that Starain mentioned useful for you?

**Comment by AlexRukhlin** [comment]
Fixed in commit [4d2b7bd](https://github.com/Microsoft/team-explorer-everywhere/commit/4d2b7bd116fb5e30827365838b7594ffa638c1a5).

Thanks.
