### ISSUE TITLE
TEE: java.lang.NullPointerException

### ISSUE THREAD

**Issue by and146** [microsoft/team-explorer-everywhere#187]
I am experiencing a java.lang.NullPointerException when getting a last version of a directory in TFS (see the stack trace below).

- TEE plug-in version: 14.114.0.201703081735
- Eclipse version: 4.5.2 (Mars 2) - 32-bit
- It is strange that when I localize the file on which the NullPointerException is thrown, I can download it manually, but in another attempt to get the remaining files from the top level, the NullPointerException occurs again on a different file etc. All those files are plain-text XML.
- Workaround: I can get the content of the TFS directory by getting it "subdirectory by subdirectory", but this is far from ideal.
- Stack trace:

2017-04-21 14:02:44,659 ERROR [ModalContext] (com.microsoft.tfs.client.common.framework.resources.command.WorkspaceCommand) Workspace command error
com.microsoft.tfs.core.clients.versioncontrol.exceptions.VersionControlException: java.lang.NullPointerException
	at com.microsoft.tfs.core.clients.versioncontrol.engines.internal.GetEngine.throwIfFatalError(GetEngine.java:2958)
	at com.microsoft.tfs.core.clients.versioncontrol.engines.internal.GetEngine.processOperationsInternal(GetEngine.java:1142)
	at com.microsoft.tfs.core.clients.versioncontrol.engines.internal.GetEngine.processOperations(GetEngine.java:957)
	at com.microsoft.tfs.core.clients.versioncontrol.engines.internal.GetEngine.processGetOperations(GetEngine.java:808)
	at com.microsoft.tfs.core.clients.versioncontrol.soapextensions.Workspace.get(Workspace.java:2463)
	at com.microsoft.tfs.core.clients.versioncontrol.soapextensions.Workspace.get(Workspace.java:2345)
	at com.microsoft.tfs.client.common.commands.vc.GetCommand.doRun(GetCommand.java:96)
	at com.microsoft.tfs.client.common.framework.command.Command.run(Command.java:92)
	at com.microsoft.tfs.client.common.framework.resources.command.WorkspaceRunnableCommandAdapter.run(WorkspaceRunnableCommandAdapter.java:69)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at com.microsoft.tfs.client.common.framework.resources.command.WorkspaceCommand.run(WorkspaceCommand.java:204)
	at com.microsoft.tfs.client.common.framework.resources.command.ResourceChangingCommand.run(ResourceChangingCommand.java:37)
	at com.microsoft.tfs.client.common.ui.framework.command.RunnableWithProgressCommandAdapter.run(RunnableWithProgressCommandAdapter.java:65)
	at com.microsoft.tfs.client.common.ui.framework.runnable.DeferredProgressMonitorDialogContext$RunnableWithProgressWrapper.run(DeferredProgressMonitorDialogContext.java:249)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: java.lang.NullPointerException
	at com.microsoft.tfs.core.clients.versioncontrol.VersionControlClient.downloadFileToStreamsInternal(VersionControlClient.java:2633)
	at com.microsoft.tfs.core.clients.versioncontrol.VersionControlClient.downloadFileToStreams(VersionControlClient.java:2490)
	at com.microsoft.tfs.core.clients.versioncontrol.engines.internal.workers.GetDownloadWorker.downloadFile(GetDownloadWorker.java:306)
	at com.microsoft.tfs.core.clients.versioncontrol.engines.internal.workers.GetDownloadWorker.call(GetDownloadWorker.java:157)
	at com.microsoft.tfs.core.clients.versioncontrol.engines.internal.workers.GetDownloadWorker.call(GetDownloadWorker.java:72)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at com.microsoft.tfs.core.clients.versioncontrol.internal.concurrent.BoundedExecutor$1.run(BoundedExecutor.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2017-04-21 14:02:47,295 ERROR [main] (com.microsoft.tfs.client.common.commands.vc.GetCommand) java.lang.NullPointerException (java.lang.NullPointerException)
com.microsoft.tfs.core.clients.versioncontrol.exceptions.VersionControlException: java.lang.NullPointerException
	at com.microsoft.tfs.core.clients.versioncontrol.engines.internal.GetEngine.throwIfFatalError(GetEngine.java:2958)
	at com.microsoft.tfs.core.clients.versioncontrol.engines.internal.GetEngine.processOperationsInternal(GetEngine.java:1142)
	at com.microsoft.tfs.core.clients.versioncontrol.engines.internal.GetEngine.processOperations(GetEngine.java:957)
	at com.microsoft.tfs.core.clients.versioncontrol.engines.internal.GetEngine.processGetOperations(GetEngine.java:808)
	at com.microsoft.tfs.core.clients.versioncontrol.soapextensions.Workspace.get(Workspace.java:2463)
	at com.microsoft.tfs.core.clients.versioncontrol.soapextensions.Workspace.get(Workspace.java:2345)
	at com.microsoft.tfs.client.common.commands.vc.GetCommand.doRun(GetCommand.java:96)
	at com.microsoft.tfs.client.common.framework.command.Command.run(Command.java:92)
	at com.microsoft.tfs.client.common.framework.resources.command.WorkspaceRunnableCommandAdapter.run(WorkspaceRunnableCommandAdapter.java:69)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at com.microsoft.tfs.client.common.framework.resources.command.WorkspaceCommand.run(WorkspaceCommand.java:204)
	at com.microsoft.tfs.client.common.framework.resources.command.ResourceChangingCommand.run(ResourceChangingCommand.java:37)
	at com.microsoft.tfs.client.common.ui.framework.command.RunnableWithProgressCommandAdapter.run(RunnableWithProgressCommandAdapter.java:65)
	at com.microsoft.tfs.client.common.ui.framework.runnable.DeferredProgressMonitorDialogContext$RunnableWithProgressWrapper.run(DeferredProgressMonitorDialogContext.java:249)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: java.lang.NullPointerException
	at com.microsoft.tfs.core.clients.versioncontrol.VersionControlClient.downloadFileToStreamsInternal(VersionControlClient.java:2633)
	at com.microsoft.tfs.core.clients.versioncontrol.VersionControlClient.downloadFileToStreams(VersionControlClient.java:2490)
	at com.microsoft.tfs.core.clients.versioncontrol.engines.internal.workers.GetDownloadWorker.downloadFile(GetDownloadWorker.java:306)
	at com.microsoft.tfs.core.clients.versioncontrol.engines.internal.workers.GetDownloadWorker.call(GetDownloadWorker.java:157)
	at com.microsoft.tfs.core.clients.versioncontrol.engines.internal.workers.GetDownloadWorker.call(GetDownloadWorker.java:72)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at com.microsoft.tfs.core.clients.versioncontrol.internal.concurrent.BoundedExecutor$1.run(BoundedExecutor.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by madhurig** [comment]
@and146: It looks like your workspace / setup is incorrect. How did you create the workspace? Was it created in TEE? It is unclear what you mean by "localize" the file. Are you trying to fetch the individual files? Please check if the workspace is a server or local workspace. 

You can try a few things:
1. Increase the memory in the eclipse.ini: https://wiki.eclipse.org/FAQ_How_do_I_increase_the_heap_size_available_to_Eclipse%3F
2. Try creating a new TFS workspace via TEE.
