### ISSUE TITLE
Unable to run teeclc on AIX server when using 64 bit version of Java

### ISSUE THREAD

**Issue by chapmasc** [Microsoft/team-explorer-everywhere#246]
Receive the following error when attempting to run any tf command on an AIX server unless I explicitly tell it to run against a 32 bit version of java.

Exception in thread "main" java.lang.UnsatisfiedLinkError: com/microsoft/tfs/jni/internal/platformmisc/NativePlatformMisc.nativeGetEnvironmentVariable(Ljava/lang/String;)Ljava/lang/String;

        at com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.getEnvironmentVariable(NativePlatformMisc.java:121)
         at com.microsoft.tfs.jni.PlatformMiscUtils.getEnvironmentVariable(PlatformMiscUtils.java:47)
         at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.makeDirectoryForVendorApplicationVersion(VersionedVendorFilesystemPersistenceStore.java:96)
         at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.<init>(VersionedVendorFilesystemPersistenceStore.java:60)
         at com.microsoft.tfs.core.config.persistence.DefaultPersistenceStoreProvider.<clinit>(DefaultPersistenceStoreProvider.java:42)
         at java.lang.J9VMInternals.initializeImpl(Native Method)
         at java.lang.J9VMInternals.initialize(J9VMInternals.java:199)
         at com.microsoft.tfs.client.common.logging.TELoggingConfiguration.configure(TELoggingConfiguration.java:38)
         at com.microsoft.tfs.client.clc.vc.Main.main(Main.java:23)

After updating the tf file to point to a 32 bit version of Java though, then it worked successfully.

Before: exec java -Xmx2048M -classpath "$CLC_CLASSPATH" $TF_ADDITIONAL_JAVA_ARGS \
After: exec /usr/java6/bin/java -Xmx2048M -classpath "$CLC_CLASSPATH" $TF_ADDITIONAL_JAVA_ARGS \

**Comment by chapmasc** [comment]
Almost forgot.  This is using the latest release (14.123.1)
