### ISSUE TITLE
Work Item Client connection reset due to XML ParseError

### ISSUE THREAD

**Issue by louis-belleville** [microsoft/team-explorer-everywhere#277]
Getting a connection error when the Work Item Client tries to pre-cache the metadata of a TFS collection with a large number of projects (~600).

This is the stack trace of the error:

`		javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,9532590]
Message: Connection reset
		at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:599)
		at com.microsoft.tfs.core.ws.runtime.stax.StaxUtils.copyCurrentElement(StaxUtils.java:194)
		at com.microsoft.tfs.core.ws.runtime.types.StaxAnyContentType.readFromElement(StaxAnyContentType.java:215)
		at ms.tfs.workitemtracking.clientservices._03._ClientService5Soap_GetMetadataEx2Response.readFromElement(_ClientService5Soap_GetMetadataEx2Response.java:141)
		at ms.tfs.workitemtracking.clientservices._03._ClientService5Soap12Service$34.readSOAPResponse(_ClientService5Soap12Service.java:874)
		at com.microsoft.tfs.core.ws.runtime.client.SOAPService.executeSOAPRequestInternal(SOAPService.java:614)
		at com.microsoft.tfs.core.ws.runtime.client.SOAPService.executeSOAPRequestInternal(SOAPService.java:617)
		at com.microsoft.tfs.core.ws.runtime.client.SOAPService.executeSOAPRequest(SOAPService.java:444)
		at ms.tfs.workitemtracking.clientservices._03._ClientService5Soap12Service.getMetadataEx2(_ClientService5Soap12Service.java:864)
		at com.microsoft.tfs.core.clients.workitem.internal.metadata.Metadata.update(Metadata.java:479)
		at com.microsoft.tfs.core.clients.workitem.internal.metadata.Metadata.update(Metadata.java:458)
		at com.microsoft.tfs.core.clients.workitem.internal.WITContext.<init>(WITContext.java:101)
		at com.microsoft.tfs.core.clients.workitem.WorkItemClient.getContext(WorkItemClient.java:394)
		at com.microsoft.tfs.core.clients.workitem.WorkItemClient.precacheData(WorkItemClient.java:321)	`

The following error also occurs, but is most likely related to the previous one:

`		java.lang.OutOfMemoryError: GC overhead limit exceeded
		at java.util.jar.Attributes.<init>(Attributes.java:74)
		at java.util.jar.Manifest.read(Manifest.java:248)
		at java.util.jar.Manifest.<init>(Manifest.java:69)
		at java.util.jar.JarFile.getManifestFromReference(JarFile.java:194)
		at java.util.jar.JarFile.getManifest(JarFile.java:180)
		at sun.net.www.protocol.jar.URLJarFile.isSuperMan(URLJarFile.java:174)
		at sun.net.www.protocol.jar.URLJarFile.getManifest(URLJarFile.java:142)
		at java.util.jar.JarFile.maybeInstantiateVerifier(JarFile.java:344)
		at java.util.jar.JarFile.getInputStream(JarFile.java:445)
		at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:164)
		at java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:238)
		at java.lang.Class.getResourceAsStream(Class.java:2223)
		at com.microsoft.tfs.core.internal.db.Configuration.<init>(Configuration.java:35)
		at com.microsoft.tfs.core.internal.db.ConnectionConfiguration.<init>(ConnectionConfiguration.java:72)
		at com.microsoft.tfs.core.internal.db.ConnectionConfiguration.<init>(ConnectionConfiguration.java:63)
		at com.microsoft.tfs.core.clients.workitem.internal.WITContext.<init>(WITContext.java:85)
		at com.microsoft.tfs.core.clients.workitem.WorkItemClient.getContext(WorkItemClient.java:394)
		at com.microsoft.tfs.core.clients.workitem.WorkItemClient.precacheData(WorkItemClient.java:321)`

This error is somewhat known as seen by this forum post: [https://developercommunity.visualstudio.com/content/problem/231495/eclipse-plugin-connection-reset.html](https://developercommunity.visualstudio.com/content/problem/231495/eclipse-plugin-connection-reset.html)

These errors are happening on TFS 2015 Update 2 with TEE 14.120, but given that the key parts of the code haven't changed there's no reason to believe it doesn't happen on latest.

edit:

**Update**: 
While the exception thrown is an XMLStreamException, the underlying cause of this exception has nothing to do with parsing and is most likely a Socket Exception (whose trace is unfortunately swallowed by Java's XMLStreamReader implementation). The logs on both the client and server say little about what causes this Socket Exception though--there is an entry in IIS's HTTPERR log, but all it says is that: "HTTP/1.1 POST /tfs/[CollectionName]/WorkItemTracking/v5.0/ClientService.asmx - 2 Connection_Dropped Microsoft+Team+Foundation+Server+Application+Pool".

Furthermore while this error has so far only happened in Collections with many hundreds of projects, it doesn't happen in all installations with that many projects in the Collection which suggests that this bug may depend on TFS or ASP.net or IIS server configurations.

One thing that can cause this exact error is the worker in the Application Pool getting recycled during the GetMetadataEx2 request to the ClientService. However this doesn't seem to be what is causing the error given that this exception is thrown for a particular collection only ~30 seconds after the request is sent.

**Update 2**
This problem seems to also be caused by having a load balancer without sticky sessions enabled with the 'connection dropped' happening when the load balancer causes the batched called to switch instance.

**Comment by eric-milles** [comment]
#310
