### ISSUE TITLE
Dependency java.xml.bind removed in Java 11

### ISSUE THREAD

**Issue by Pingulea** [microsoft/team-explorer-everywhere#289]
I'm trying to simply use the command-line client, after having installed Java 11.
But there is a dependency of TEE on javax.xml.bind. JAXB APIs are considered to be Java EE APIs; removed from Java 11, as per below:
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j
Hence, TF is simply failing when I try to run it on my Linux. Log says:
```
2018-12-21 02:44:51,653 ERROR [main] (com.microsoft.tfs.client.clc.vc.Main) Unhandled exception reached Main: 
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.<init>(TelemetryConfigurationFactory.java:65)
	at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.<clinit>(TelemetryConfigurationFactory.java:54)
	at com.microsoft.applicationinsights.TelemetryConfiguration.getActive(TelemetryConfiguration.java:72)
	at com.microsoft.tfs.core.telemetry.TfsTelemetryHelper.initializeTelemetryChannel(TfsTelemetryHelper.java:43)
	at com.microsoft.tfs.core.telemetry.TfsTelemetryHelper.getTelemetryClient(TfsTelemetryHelper.java:58)
	at com.microsoft.tfs.core.telemetry.TfsTelemetryHelper.sendSessionBegins(TfsTelemetryHelper.java:138)
	at com.microsoft.tfs.client.clc.Application.run(Application.java:153)
	at com.microsoft.tfs.client.clc.vc.Main.main(Main.java:55)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 8 more
2018-12-21 02:44:51,655 INFO  [main] (com.microsoft.tfs.client.clc.vc.Main) Shutting down
2018-12-21 02:44:51,668 INFO  [main] (com.microsoft.tfs.client.clc.vc.Main) Has shut down
```

**Comment by nfantone** [comment]
Reverting back to Java 8, solves the issue. For Java 9/10, you can [manually follow these instructions](https://expicon.se/2017/10/13/tee-clc-not-working-on-mac/).

**Comment by qidydl** [comment]
Java 11 is failing for me as well, but completely silently--even editing the tf shell script to add -verbose provides barely any information. At the very least, could the documentation be updated to indicate that Java 11 is not supported?

**Comment by renejesusgv** [comment]
As @qidydl noticed, Java 11 falls silently. I installed Java 8 and it works like a charm. If you are using Ubuntu or derivates see  https://askubuntu.com/a/1137788

**Comment by nitinupreti** [comment]
Hi all,

I followed the same steps as mentioned in [link](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j) for JDK 11 by adding maven dependencies in POM file but the issue still not resolved and getting the same error as mentioned below.

[ERROR] Exit code: 1 - javadoc: warning - The old Doclet and Taglet APIs in the packages
[ERROR] com.sun.javadoc, com.sun.tools.doclets and their implementations
[ERROR] are planned to be removed in a future JDK release. These
[ERROR] components have been superseded by the new APIs in jdk.javadoc.doclet.
[ERROR] Users are strongly recommended to migrate to the new APIs.
[ERROR] java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
[ERROR]         at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
[ERROR]         at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
[ERROR]         at java.base/java.lang.Class.getMethodsRecursive(Class.java:3308)
[ERROR]         at java.base/java.lang.Class.getMethod0(Class.java:3294)
[ERROR]         at java.base/java.lang.Class.getMethod(Class.java:2107)
[ERROR]         at jdk.javadoc/com.sun.tools.javadoc.main.DocletInvoker.invoke(DocletInvoker.java:309)
[ERROR]         at jdk.javadoc/com.sun.tools.javadoc.main.DocletInvoker.optionLength(DocletInvoker.java:236)
[ERROR]         at jdk.javadoc/com.sun.tools.javadoc.main.Start.parseAndExecute(Start.java:341)
[ERROR]         at jdk.javadoc/com.sun.tools.javadoc.main.Start.begin(Start.java:238)
[ERROR]         at jdk.javadoc/com.sun.tools.javadoc.main.Start.begin(Start.java:224)
[ERROR]         at jdk.javadoc/com.sun.tools.javadoc.Main.execute(Main.java:174)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:419)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:344)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
[ERROR]         at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
[ERROR] Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
[ERROR]         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[ERROR]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[ERROR]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[ERROR]         ... 15 more
[ERROR] javadoc: error - fatal error
