### ISSUE TITLE
Impossible to get Solution from TF Source Control.

### ISSUE THREAD

**Issue by Lionberg** [microsoft/team-explorer-everywhere#319]
com.microsoft.alm.plugin.external.exceptions.ToolBadExitCodeException: KEY_TF_BAD_EXIT_CODE
	at com.microsoft.alm.plugin.external.tools.TfTool.throwBadExitCode(TfTool.java:109)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:180)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)

**Comment by ForNeVeR** [comment]
In case it is an error message from IntelliJ plugin, you better report it to the Azure DevOps IntelliJ repository: https://github.com/microsoft/azure-devops-intellij/issues
