### ISSUE TITLE
Tee 14.135.0 requires slf4j-api-1.7.19.jar, slf4j-log4j12-1.7.19.jar for gnomekeyring?

### ISSUE THREAD

**Issue by JonathonQuinn** [microsoft/team-explorer-everywhere#323]
Tee 14.135.0 looks very promising (fixing build failures with Azure DevOps 2020 Rc1)
https://github.com/Microsoft/team-explorer-everywhere/releases
But after upgrading tee to 14.135.0.202010141426 on ubuntu 18.04 it now fails

I copied slf4j-api-1.7.19.jar, slf4j-log4j12-1.7.19.jar from 14.134.0.201804261732 and then it worked

```
2020-10-21 22:59:30,305 DEBUG [main] (com.microsoft.tfs.client.clc.vc.Main) Entering Main
2020-10-21 22:59:30,308 DEBUG [main] (com.microsoft.tfs.jni.loader.NativeLoader) Loading library native_console
2020-10-21 22:59:30,308 DEBUG [main] (com.microsoft.tfs.jni.loader.NativeLoader) Property com.microsoft.tfs.jni.native.base-directory set to /home/linuxbuildagent/agent03/externals/tee/native; only looking there for native libraries
2020-10-21 22:59:30,308 DEBUG [main] (com.microsoft.tfs.jni.loader.NativeLoader) Trying to load native library file /home/linuxbuildagent/agent03/externals/tee/native/linux/x86_64/libnative_console.so
2020-10-21 22:59:30,308 DEBUG [main] (com.microsoft.tfs.jni.loader.NativeLoader) Loaded /home/linuxbuildagent/agent03/externals/tee/native/linux/x86_64/libnative_console.so from user-specified directory
2020-10-21 22:59:30,308 DEBUG [main] (com.microsoft.tfs.jni.loader.NativeLoader) Successfully loaded native library native_console
2020-10-21 22:59:30,326 DEBUG [main] (com.microsoft.tfs.client.clc.Application) Entering CLC application
2020-10-21 22:59:30,326 DEBUG [main] (com.microsoft.tfs.client.clc.Application) Command line: 
2020-10-21 22:59:30,326 DEBUG [main] (com.microsoft.tfs.client.clc.Application)      args[0]: workspaces
2020-10-21 22:59:30,326 DEBUG [main] (com.microsoft.tfs.client.clc.Application)      args[1]: -format:xml
2020-10-21 22:59:30,326 DEBUG [main] (com.microsoft.tfs.client.clc.Application)      args[2]: -collection:<redacted>
2020-10-21 22:59:30,327 DEBUG [main] (com.microsoft.tfs.client.clc.Application)      args[3]: -jwt:<redacted>
2020-10-21 22:59:30,327 DEBUG [main] (com.microsoft.tfs.client.clc.Application)      args[4]: -noprompt
2020-10-21 22:59:30,400 DEBUG [main] (com.microsoft.tfs.client.clc.Application) Parse and prepare arguments.
2020-10-21 22:59:30,422 DEBUG [main] (com.microsoft.tfs.client.clc.Application) Execute the command implementation.
2020-10-21 22:59:30,433 DEBUG [main] (com.microsoft.tfs.core.persistence.FilesystemPersistenceStore) retrieveObject called for com.microsoft.tfs.client.productid.xml
2020-10-21 22:59:30,434 DEBUG [main] (com.microsoft.tfs.core.persistence.FilesystemPersistenceStore) Reading object file /home/linuxbuildagent/.microsoft/Team Foundation/4.0/Configuration/TEE-Mementos/com.microsoft.tfs.client.productid.xml
2020-10-21 22:59:30,457 DEBUG [main] (com.microsoft.tfs.core.persistence.FilesystemPersistenceStore) Done reading object file /home/linuxbuildagent/.microsoft/Team Foundation/4.0/Configuration/TEE-Mementos/com.microsoft.tfs.client.productid.xml
2020-10-21 22:59:30,837 ERROR [main] (com.microsoft.tfs.client.clc.Application) Unexpected exception: 
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.microsoft.alm.storage.posix.internal.GnomeKeyringBackedSecureStore.<clinit>(GnomeKeyringBackedSecureStore.java:15)
	at com.microsoft.tfs.core.credentials.internal.GnomeKeyringCredentialsManager.<clinit>(GnomeKeyringCredentialsManager.java:23)
	at com.microsoft.tfs.core.credentials.CredentialsManagerFactory.getCredentialsManager(CredentialsManagerFactory.java:91)
	at com.microsoft.tfs.client.clc.commands.Command.createConnection(Command.java:1537)
	at com.microsoft.tfs.client.clc.commands.Command.createConnection(Command.java:1358)
	at com.microsoft.tfs.client.clc.vc.commands.CommandWorkspaces.displayAndUpdate(CommandWorkspaces.java:294)
	at com.microsoft.tfs.client.clc.vc.commands.CommandWorkspaces.run(CommandWorkspaces.java:93)
	at com.microsoft.tfs.client.clc.Application.run(Application.java:297)
	at com.microsoft.tfs.client.clc.Application.run(Application.java:147)
	at com.microsoft.tfs.client.clc.vc.Main.main(Main.java:55)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 10 more
2020-10-21 22:59:30,839 DEBUG [main] (com.microsoft.tfs.client.clc.Application) Leaving CLC application
2020-10-21 22:59:30,839 INFO  [main] (com.microsoft.tfs.client.clc.vc.Main) Shutting down
2020-10-21 22:59:30,840 DEBUG [main] (com.microsoft.tfs.util.shutdown.ShutdownManager) shutdown
2020-10-21 22:59:30,852 INFO  [main] (com.microsoft.tfs.client.clc.vc.Main) Has shut down
2020-10-21 22:59:30,855 DEBUG [Thread-0] (com.microsoft.tfs.util.shutdown.ShutdownManager) shutdown
```

**Comment by chriskarel** [comment]
I can confirm this bug.  Ran into the same issue on a RHEL7 based distro.  Copied the slf4j-* files from an older release, and the CLC works properly.

Thanks for the issue writeup, @JonathonQuinn
