### ISSUE TITLE
Error when trying to manually install on MacOS Big Sur

### ISSUE THREAD

**Issue by Ibrahim-Islam** [microsoft/team-explorer-everywhere#327]
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.nativeGetEnvironmentVariable(Ljava/lang/String;)Ljava/lang/String;
	at com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.nativeGetEnvironmentVariable(Native Method)
	at com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.getEnvironmentVariable(NativePlatformMisc.java:121)
	at com.microsoft.tfs.jni.PlatformMiscUtils.getEnvironmentVariable(PlatformMiscUtils.java:47)
	at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.makeDirectoryForVendorApplicationVersion(VersionedVendorFilesystemPersistenceStore.java:96)
	at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.<init>(VersionedVendorFilesystemPersistenceStore.java:60)
	at com.microsoft.tfs.core.config.persistence.DefaultPersistenceStoreProvider.<clinit>(DefaultPersistenceStoreProvider.java:42)
	at com.microsoft.tfs.client.common.logging.TELoggingConfiguration.configure(TELoggingConfiguration.java:38)
	at com.microsoft.tfs.client.clc.vc.Main.main(Main.java:23)
```

**Comment by thomasfdm** [comment]
I found that it's because OSX didn't like the file “libnative_misc.jnilib” because it couldn't verify it. Found a solution here that worked for me: https://github.com/microsoft/team-explorer-everywhere/issues/317

**Comment by Ibrahim-Islam** [comment]
I get this error when running that tool:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'CoreFoundation':
dlopen(libCoreFoundation.dylib, 9): image not found
dlopen(libCoreFoundation.dylib, 9): image not found
```

**Comment by Ibrahim-Islam** [comment]
Finally after clicking through multiple "Allow..." the `tf` command work and then I went ahead with using Rider with it and finally got a complete solution.
