### ISSUE TITLE
Developer Cannot Be Verified

### ISSUE THREAD

**Issue by blanthor** [microsoft/team-explorer-everywhere#333]
# Environment 
macOS version 10.15.7 Catalina
Downloaded and extracted TEE-CLC-14.135.0 

I tried running TEE-CLC-14.135.0/tf and received the following error messages 

### Popup Message
“libnative_misc.jnilib” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.
### Exception message 
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'java.lang.String com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.nativeGetEnvironmentVariable(java.lang.String)'
	at com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.nativeGetEnvironmentVariable(Native Method)
	at com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.getEnvironmentVariable(NativePlatformMisc.java:121)
	at com.microsoft.tfs.jni.PlatformMiscUtils.getEnvironmentVariable(PlatformMiscUtils.java:47)
	at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.makeDirectoryForVendorApplicationVersion(VersionedVendorFilesystemPersistenceStore.java:97)
	at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.<init>(VersionedVendorFilesystemPersistenceStore.java:60)
	at com.microsoft.tfs.core.config.persistence.DefaultPersistenceStoreProvider.<clinit>(DefaultPersistenceStoreProvider.java:42)
	at com.microsoft.tfs.client.common.logging.TELoggingConfiguration.configure(TELoggingConfiguration.java:38)
	at com.microsoft.tfs.client.clc.vc.Main.main(Main.java:23)
ralph.compton@AMAC02Z78KQLVDQ ~ % ./TEE-CLC-14.135.0/tf
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'java.lang.String com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.nativeGetEnvironmentVariable(java.lang.String)'
	at com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.nativeGetEnvironmentVariable(Native Method)
	at com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.getEnvironmentVariable(NativePlatformMisc.java:121)
	at com.microsoft.tfs.jni.PlatformMiscUtils.getEnvironmentVariable(PlatformMiscUtils.java:47)
	at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.makeDirectoryForVendorApplicationVersion(VersionedVendorFilesystemPersistenceStore.java:97)
	at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.<init>(VersionedVendorFilesystemPersistenceStore.java:60)
	at com.microsoft.tfs.core.config.persistence.DefaultPersistenceStoreProvider.<clinit>(DefaultPersistenceStoreProvider.java:42)
	at com.microsoft.tfs.client.common.logging.TELoggingConfiguration.configure(TELoggingConfiguration.java:38)
	at com.microsoft.tfs.client.clc.vc.Main.main(Main.java:23)

**Comment by yoongshang** [comment]
Hi, you can just "Allow" it (App Store and identified developers ) on System Reference -> Security & Privacy 
<img width="700" alt="image" src="https://user-images.githubusercontent.com/15799830/106360730-22ac0180-6355-11eb-8fc2-f92240d6b0f4.png">
