### ISSUE TITLE
Importing Team Project Set fails

### ISSUE THREAD

**Issue by Ponai** [Microsoft/team-explorer-everywhere#50]
When trying to import a Team Project Set (psf file) from within Eclipse, that is created with the Team Project Set export functionality, we get the following error:

`eclipse.buildId=M20130204-1200
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

Error
Tue Apr 12 17:29:59 CEST 2016
An error occurred importing this project set.

org.eclipse.team.core.TeamException: The following errors occurred while importing projects. Some projects may not be loaded.
	at org.eclipse.team.internal.ui.ProjectSetImporter.importProjectSet(ProjectSetImporter.java:123)
	at org.eclipse.team.internal.ui.ProjectSetImporter.importProjectSet(ProjectSetImporter.java:67)
	at org.eclipse.team.internal.ui.actions.ImportProjectSetAction$1.execute(ImportProjectSetAction.java:48)
	at org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(WorkspaceModifyOperation.java:106)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2344)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:118)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
Contains: Failed to load projects
`
Contents of psf file (obfuscated server name and project names etc.):
`
<?xml version="1.0" encoding="UTF-8"?>
<psf version="2.0">
<provider id="com.microsoft.tfs.client.eclipse.TFSRepositoryProvider">
<project reference="http://server:8080/tfs/DefaultCollection/;$/Project/level1/project"/>
</provider>
</psf>
`
Version of Eclipse: 4.2.2
Version of plugin:  14.0.3.201603291051

**Comment by DavidStaheli** [comment]
Hi Ponai, sorry for the trouble.  We'll investigate this problem and try to address it as soon as possible.  Thank you for the report!

**Comment by valmatr** [comment]
Hi,

I am seeing similar exception when trying to import PSF file (please exception see below). PSF is generated via Eclipse and references existing TFS project.

Eclipse 4.9.0
Team Explorer Everywhere	14.134.0.201804261733

Could you please advise if there are plans to fix the issue or any proposed workarounds?

Thank you.


java.lang.reflect.InvocationTargetException
	at org.eclipse.team.internal.ui.ProjectSetImporter.importProjectSet(ProjectSetImporter.java:188)
	at org.eclipse.team.internal.ui.ProjectSetImporter.importProjectSetFromString(ProjectSetImporter.java:55)
	at org.eclipse.oomph.setup.projectset.impl.ProjectSetImportTaskImpl$Helper$1.perform(ProjectSetImportTaskImpl.java:284)
	at org.eclipse.oomph.setup.projectset.impl.ProjectSetImportTaskImpl$Helper.perform(ProjectSetImportTaskImpl.java:286)
	at org.eclipse.oomph.setup.projectset.impl.ProjectSetImportTaskImpl.perform(ProjectSetImportTaskImpl.java:224)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3334)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3277)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4504)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2319)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4498)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4496)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3268)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3243)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3143)
	at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:575)
	at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:701)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.team.core.TeamException: The following errors occurred while importing projects. Some projects may not be loaded.
	at org.eclipse.team.internal.ui.ProjectSetImporter.importProjectSet(ProjectSetImporter.java:126)
	... 17 more
